server:
  port: 8888
spring:
  profiles:
    include: native
  native:
    searchLocations: classpath:/shared
  cloud:
    config:
      server:
        native:
          search-locations: [ classpath:/shared ]
  application:
    name: config-service
management:
  endpoints:
    web:
      exposure:
        include: "*"
