server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
logging:
  pattern:
    console: "[%-5level] %d{HH:mm:ss} - %msg%n"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      ddl-auto: update
    show-sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  token:
    secret: 1234566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expired: 3600000
